max_stag/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stag.urls'), name='stag'),
    path('polls/', include('poll.urls'), name='poll'),
    path('accounts/', include('django.contrib.auth.urls'))
]

poll/urls.py
from django.urls import path
from .views import QuestionListView, QuestionDetailView


app_name = 'poll'

urlpatterns = [
    path('', QuestionListView.as_view(), name='list'),
    path('<int:pk>', QuestionDetailView.as_view(), name='detail')
]

stag/urls.py
from django.urls import path, include
from .views import QuestionListView, HomeView

app_name = 'stag'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('questions/', QuestionListView.as_view(), name='questions')
]

poll/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.shortcuts import reverse


# Create your models here.
class Question(models.Model):
    # created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField(blank=True)
    multiple_choices = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        """On save, update the timestamps"""
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('poll:detail', args=[str(self.pk)])


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField(blank=True)
    voted_by = models.ManyToManyField(User, blank=True)
    choice = models.CharField(max_length=50)

    def save(self, *args, **kwargs):
        """On save, update the timestamps"""
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(Answer, self).save(*args, **kwargs)

    def _votes(self):
        return self.voted_by.count()

    def __str__(self):
        return self.choice

    votes = property(_votes)

stag/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, related_name='questions')
    title = models.CharField(max_length=80)
    question = models.TextField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return self.title


class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'{self.question}: {self.author} - {self.created_on:%Y-%m-%d}'

stag_calendar/models.py
from django.db import models

# Create your models here.

poll/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Question, Answer
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class QuestionListView(LoginRequiredMixin, ListView):
    template_name = 'poll/poll_list.html'
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        voted = Question.objects.filter(answer__voted_by=self.request.user.id)
        context['voted'] = voted
        return context
    

class QuestionDetailView(LoginRequiredMixin, DetailView):
    model = Question
    template_name = 'poll/poll_detail.html'

stag/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import Question
# Create your views here.


class QuestionListView(ListView):
    model = Question
    template_name = 'stag/question_list.html'


class HomeView(TemplateView):
    template_name = 'stag/home.html'

stag_calendar/views.py
from django.shortcuts import render

# Create your views here.

poll/templates/poll/poll_detail.html
{% extends 'components/base.html' %}

{% block fadein %}
    <h1>{{ question.title }}</h1>
    <p>{{ question.body }}</p>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.choice }}: {{ answer.votes }} Vote{{ answer.votes|pluralize }}</li>
    {% endfor %}
    </ul>
{% endblock %}

poll/templates/poll/poll_list.html
{% extends 'components/base.html' %}

{% block fadein %}

<div class="row row-cols-1 row-cols-md-2">
    <div class="col mb-4">
    {% for question in question_list %}
        <a class="card-main" href="{{ question.get_absolute_url }}">
        <div class="card {% if question in voted %}bg-success text-white{% endif %} mb-3">
            <div class="card-body">
                <h5 class="card-text">{{ question.title }}</h5>
                <p class="card-text">{{ question.body }}</p>

            </div>
            <div class="card-footer">
                <p class="card-text">
                    <small class="{% if question in voted %}text-white{% else %}text-muted{% endif %}">
                        Last modified: {{ question.modified }}
                        {% if question in voted %}
                            <p class="cart-text">You have already voted on this question</p>
                        {% endif %}
                    </small>
                </p>
            </div>
        </div>
        </a>
    {% endfor %}
    </div>
</div>

{% endblock %}

stag/templates/stag/home.html
{% extends 'components/base.html' %}

{% load static %}

{% block content %}
    <div class="container text-center pt-5 align-middle" style="height:90vh; display: table;">
        <div style="display: table-cell; vertical-align: middle;">
            <div class="load">
                <h1>Jonathan Bleasby</h1>
            </div>
            <div class="load-2">
                <h5>StagMan</h5>
            </div>
            <div class="load-3">
                <a role="button" class="btn btn-secondary" href="{% url 'stag:questions' %}">Enter</a>
            </div>
        </div>
    </div>
{% endblock %}

stag/templates/stag/question_list.html
{% extends 'components/base.html' %}

{% block fadein %}
    <div class="container">
        <h1>Questions Asked</h1>
        Ask a Question about our dear leader and the stage events. You can also answer anyone else's questions,
        or view answers that other people have given.<br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#askAQuestion">
            Ask a Question
        </button>

        <div class="modal fade" id="askAQuestion" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
                <form method="get">
                    <div class="modal-body">

                    This is where the ask a question goes.

                    </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Post Question</button>
                  </div>
                </form>
            </div>
          </div>
        </div>
        <div class="card-columns">
        {% for question in question_list %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ question.title }}</h5>
                    <h6 class="card-title">Asked {{ question.created_on|timesince }} ago</h6>
                    {% for category in question.categories.all %}
                        <a href="#" class="card-link">#{{ category }}</a>
                    {% endfor %}<br>
                    <p class="card-text">{{ question.question|truncatechars:20 }}</p>
                </div>
                <div class="card-footer">
                    <a class="card-link" href="#">Answer</a>
                    <a class="card-link" href="#">View Responses ({{ question.comment_set.count }})</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/components/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stag/style.css' %}">
    <title>
    {% block title %}
        Stag Do
    {% endblock %}
    </title>
</head>
<body>
{% block content %}
{% endblock %}
<div class="load-quick">
{% block fadein %}
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>